### ISSUE TITLE
Senate foreign and banking committees bug fixes

### ISSUE THREAD

**Issue by TonyxSun** [TonyxSun/PressScraper#7]
See output file for details on typos

**Comment by verxia** [comment]
Fixed the banking kajority -> majority :)

For foreign, is the error the missing URL for nominations? I had difficulty extracting it before, but I got it now

**Comment by TonyxSun** [comment]
@verxia  Yep, I also fixed this (date) for banking. we can close ticket now!
ps: 
![CleanShot 2021-07-30 at 21 11 24@2x](https://user-images.githubusercontent.com/68176295/127728239-32651a99-1fbd-4fd2-9154-955da13fb998.png)
