### ISSUE TITLE
Catch empty csvs error

### ISSUE THREAD

**Issue by verxia** [TonyxSun/PressScraper#8]
If there are no recent or future news, the csv produced will be empty, which throws an error when converting the csv to a df in exporter.py. Use try/except block to catch the error (see SIA part).

**Comment by TonyxSun** [comment]
Hey, I noticed this as well. Does it interfere with the actual function? I think after it throws the error it just skips the line harmlessly

**Comment by TonyxSun** [comment]
Let me know if you want me to add exception handling to all blocks tho. I'm busy today and tomorrow, but I can work on any issues on Sunday night.

**Comment by verxia** [comment]
It halted the execution for me! We can both change it on our exporters (so mac for me, windows for you)

It might also be nice to output an error msg, eg. "No recent output from the past week or in the future".

**Comment by TonyxSun** [comment]
I think something is up. It is showing empty tables for lots of sites. I will investigate tmr (thank god for break 😄) Also, I will probably just do dev on my other laptop (mac), once I get env set up. I will move the windows versions to the backup branch and clean up the organization a bit.

**Comment by verxia** [comment]
Heyy that was my bad - I messed up the csv paths for a bunch of them (all actually yikess). But I think it's good now!

The backup branch with windows sounds good :)
